### ISSUE TITLE
Firefox webextension

### ISSUE THREAD

**Issue by JostCrow** [everhide/everbug#1]
Will there also be a firefox webextension?

**Comment by everhide** [comment]
I dont use firefox, therefore, I didn't think about it. But, as I see, Firefox the APIs are based on the Chrome devtools APIs - I'll add support for Firefox for you soon :) Thanks for the feedback!

**Comment by JostCrow** [comment]
Thanks. That would be great!

**Comment by everhide** [comment]
@JostCrow Have a fun :)
[Firefox extension](https://addons.mozilla.org/ru/firefox/addon/everbug/)

**Comment by JostCrow** [comment]
Thanks. It works great!
