### ISSUE TITLE
TypeError: cannot serialize '_io.BufferedReader' object

### ISSUE THREAD

**Issue by JostCrow** [everhide/everbug#2]
Simple way to reproduce should be to go to the admin login page.

Locally added this on line 63 in middleware.py
```
try:
    cache.set(self.request_id, self.data)
except TypeError:
    pass
```

**Comment by everhide** [comment]
As I see, django.admin.* has a many protected objects (for any inspection), so I simple exlude all admin views. I think it is more  correctly. Function profiling and queries for django.admin.* still work.
