### ISSUE TITLE
'NoneType' object has no attribute 'items' using Django Rest Framework

### ISSUE THREAD

**Issue by JostCrow** [everhide/everbug#4]
In context.py the following is happening.

![screenshot-2018-6-15 attributeerror at nl api v1 educational_product](https://user-images.githubusercontent.com/390575/41472695-7984e262-70b7-11e8-9a54-c29de9c38021.png)

**Comment by everhide** [comment]
I had not planned to use it for Django Rest Framework. 
 I'll try to fix it if you want.

**Comment by JostCrow** [comment]
If you could that would be awesome.

**Comment by everhide** [comment]
@JostCrow Done it
![screen](https://user-images.githubusercontent.com/16136087/41483789-2dbaa99e-70e3-11e8-93b0-b0cd494676a4.png)
