### ISSUE TITLE
Browser extension source?

### ISSUE THREAD

**Issue by yozlet** [everhide/everbug#5]
Everbug looks fantastic, and I'm eager to use it. However, given the power they have, I'm very wary of installing new extensions to my browser unless I have good reason to trust them. It would help a lot if I could inspect the source and build it myself. How about adding the extension sources to this repo?

**Comment by everhide** [comment]
Hi! I'm so glad you enjoyed it. Current repo relates to python package of extension and  I think it would be wrong to add source of browser-extension here. But you can download and  unpack any extension (chrome/firefox) and get  source. 

Like in this article, for example:
http://www.chrisle.me/2012/12/how-to-get-the-source-code-to-any-chrome-extension/

Also I can send you source personally. Please, tell me if you have another ideas  :)

**Comment by yozlet** [comment]
Sorry for taking so long to respond!

May I ask why you think it would be wrong to include the browser extension source to this repo? I realise that they are two different products to be built and started separately, but they are also interdependent, so should probably be versioned together in a monorepo style.

Also, including the extension source in the repo makes it much easier for other people to contribute!

**Comment by everhide** [comment]
Hi! No, you don't have to apologize, everything's fine. On the contrary, thanks for feedback.

I'll try make it in one mono-repo but I dont know how do it better. I don't want to be tangled up with their versions in future.

**Comment by yozlet** [comment]
Putting the middleware and the extension in the same repo can help keep their versions consistent:

Every time you need to make a major change, you make the changes to the middleware and the extension, committing them to the same repo. Once the new feature works on both sides, you [tag a new release](https://git-scm.com/book/en/v2/Git-Basics-Tagging). You give both the middleware and the extension the same version number; that way, you know the versions work together.

**Comment by everhide** [comment]
Thanks for the advice! I added both versions of extension (Chrome/FF), tagged them all in GIT, set the version in source code and republish in stores. Hope everything turns out all right.
