### ISSUE TITLE
feature request: ability to use with class based views

### ISSUE THREAD

**Issue by grey-olli** [everhide/everbug#6]
@everhide: excellent app, thank you! It'll be briliant if it could be used as:

```
`
@profile
class myView(ListView):
    entire_class_code_to_be_applied

`
```

To the moment (commit id ed1ca386fbb52554a1fa8fffe3a5760e3d61d0dc), it's for class methods or standalone functions only (correct me if I'm wrong).

BTW: no labels/tags to reference here - had to specify last commit.

**Comment by everhide** [comment]
Hi! Thanks for feedback.
I'll try to add support for class profiling If you show me how cProfile works with classes. I have never seen that cProfile can do it as far as I know.
