### ISSUE TITLE
issue #7: Middleware authorization error

### ISSUE THREAD

**Issue by cyberbudy** [everhide/everbug#7]
During authorization process I received this error.

```

File "/usr/local/lib/python3.7/site-packages/everbug/utils/queries.py", line 23, in query_explain
cursor.execute(sql)

django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_session_pkey"
DETAIL:  Key (session_key)=(d9lhpfy1t6ppejgciu5p8rgv2flav78h) already exists.

```

**Comment by everhide** [comment]
Hi, cyberbudy. Tell me please type of your database, django version and other third-party packages. 

![1](https://user-images.githubusercontent.com/16136087/45362959-e38f8100-b5de-11e8-895d-97eba475e78d.png)
